name: verify

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Install dependencies
      run: pip3 install online-judge-verify-helper

#    - name: Set up Rust (1.70.0)
#      run: |
#        rustup set profile minimal
#        rustup install 1.70.0
#        rustup override set nightly

    # required by cargo-udeps
#    - name: Set up Rust (nightly)
#      run: |
#        rustup set profile minimal
#        rustup install nightly
#        rustup override set nightly

    # required only if you set `languages.rust.list_dependencies_backend.kind` to `"cargo-udeps"`
#    - name: Install cargo-udeps for Rust
#      uses: baptiste0928/cargo-install@v2
#      with:
#        crate: cargo-udeps
#        version: '0.1.44'
#        args: --debug

    - name: Run tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
      run: oj-verify all
